# -*- coding: utf-8 -*-
"""Assignemtn 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cW5oTzPKq8z2uNlMAILpsFX_Xz3ZwQ1o
"""

low = int(input("Input a low number: "))
high = int(input("Input a high number: "))
x = int(input("Input a number: "))
number = 0

for i in range(low, high + 1):
  if i % x == 0:
    number += 1

print(number)

number = 0
highest = number

while number >= 0:
  number = int(input("Input an integer: "))
  if number > highest:
    highest = number

print(highest)